steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    dir: 'api'
    args: ['build', '-f', 'dockerFile', '-t', 'gcr.io/$PROJECT_ID/api', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args: ['push', 'gcr.io/$PROJECT_ID/api']
    waitFor: ['Build']

  - name: 'docker/compose:1.29.2'
    id: Deploy
    dir: 'api'
    args: ['up', '-d']
    waitFor: ['Push']
    secretEnv:
      - DB_HOST
      - DB_USERNAME
      - DB_PASSWORD
      - DB_NAME
      - JWT_SECRET
      - JWT_EXPIRE_IN
    env:
      - 'UPLOAD_TO_GCS=false'

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/db-host/versions/latest
    env: 'DB_HOST'
  - versionName: projects/$PROJECT_ID/secrets/db-username/versions/latest
    env: 'DB_USERNAME'
  - versionName: projects/$PROJECT_ID/secrets/db-password/versions/latest
    env: 'DB_PASSWORD'
  - versionName: projects/$PROJECT_ID/secrets/db-name/versions/latest
    env: 'DB_NAME'
  - versionName: projects/$PROJECT_ID/secrets/JWT_SECRET/versions/latest
    env: 'JWT_SECRET'
  - versionName: projects/$PROJECT_ID/secrets/JWT_EXPIRE_IN/versions/latest
    env: 'JWT_EXPIRE_IN'

logsBucket: 'gs://lottocat_bucket/logs'