steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    dir: 'api'
    args: ['build', '--no-cache', '-f', 'dockerFile', '-t', 'gcr.io/$PROJECT_ID/api', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args: ['push', 'gcr.io/$PROJECT_ID/api']
    waitFor: ['Build']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy
    args:
      - 'run'
      - 'deploy'
      - 'lottocat'
      - '--image'
      - 'gcr.io/$PROJECT_ID/api'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--set-secrets'
      - 'DB_HOST=projects/$PROJECT_ID/secrets/db-host/versions/latest'
      - '--set-secrets'
      - 'DB_USERNAME=projects/$PROJECT_ID/secrets/db-username/versions/latest'
      - '--set-secrets'
      - 'DB_PASSWORD=projects/$PROJECT_ID/secrets/db-password/versions/latest'
      - '--set-secrets'
      - 'DB_NAME=projects/$PROJECT_ID/secrets/db-name/versions/latest'
      - '--set-secrets'
      - 'JWT_SECRET=projects/$PROJECT_ID/secrets/JWT_SECRET/versions/latest'
      - '--set-secrets'
      - 'JWT_EXPIRE_IN=projects/$PROJECT_ID/secrets/JWT_EXPIRE_IN/versions/latest'
      - '--set-secrets'
      - 'IS_SIGN=projects/$PROJECT_ID/secrets/IS_SIGN/versions/latest'
      - '--set-env-vars'
      - 'UPLOAD_TO_GCS=true'
    waitFor: ['Push']
