steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    dir: 'api'
    args: ['build', '-f', 'dockerFile', '-t', 'gcr.io/$PROJECT_ID/api', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args: ['push', 'gcr.io/$PROJECT_ID/api']
    waitFor: ['Build']

  - name: 'docker/compose:1.29.2'
    dir: 'api'
    args: ['up', '-d']
    waitFor: ['Push']