CREATE DATABASE IF NOT EXISTS locatto;
USE locatto;

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;

START TRANSACTION;
SET time_zone = "+07:00";

CREATE TABLE IF NOT EXISTS lotteries (
    lid INT AUTO_INCREMENT PRIMARY KEY,
    lottery_number VARCHAR(20) NOT NULL UNIQUE,
    period VARCHAR(50) NOT NULL,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customers (
    cid INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    telno VARCHAR(15) NOT NULL,
    img VARCHAR(255) NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    credit DECIMAL(10, 2) NOT NULL DEFAULT 0,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS purchases (
    pid INT AUTO_INCREMENT PRIMARY KEY,
    cid INT NOT NULL,
    lid INT NOT NULL,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rewards (
    rid INT AUTO_INCREMENT PRIMARY KEY,
    lid INT NOT NULL,
    tier VARCHAR(20) NOT NULL,
    revenue DECIMAL(12, 2) NOT NULL,
    winner VARCHAR(100) NULL,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE purchases ADD CONSTRAINT fk_purchases_customers FOREIGN KEY (cid) REFERENCES customers(cid) ON DELETE CASCADE;
ALTER TABLE purchases ADD CONSTRAINT fk_purchases_lotteries FOREIGN KEY (lid) REFERENCES lotteries(lid) ON DELETE CASCADE;
ALTER TABLE rewards ADD CONSTRAINT fk_rewards_lotteries FOREIGN KEY (lid) REFERENCES lotteries(lid) ON DELETE CASCADE;

COMMIT; 