SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;

START TRANSACTION;
SET time_zone = "+07:00";

CREATE TABLE IF NOT EXISTS lottery (
    lid INT AUTO_INCREMENT PRIMARY KEY,
    lottery_number VARCHAR(6) NOT NULL UNIQUE,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user (
    uid INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    telno VARCHAR(15) NOT NULL,
    img VARCHAR(255) NULL,
    email VARCHAR(255) NULL,
    card_id VARCHAR(13) NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL DEFAULT '',
    credit DECIMAL(10, 2) NOT NULL DEFAULT 0,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- ALTER TABLE user ADD COLUMN token VARCHAR(255);

CREATE TABLE IF NOT EXISTS purchase (
    pid INT AUTO_INCREMENT PRIMARY KEY,
    uid INT NOT NULL,
    lid INT NOT NULL,
    lot_amount INT NOT NULL,
    payid INT NOT NULL,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reward (
    rid INT AUTO_INCREMENT PRIMARY KEY,
    lid INT NOT NULL,
    tier VARCHAR(20) NOT NULL,
    revenue DECIMAL(12, 2) NOT NULL,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO reward (lid, tier, revenue) VALUES (null, 'Tier 1', 0, NULL);
INSERT INTO reward (lid, tier, revenue) VALUES (null, 'Tier 2', 0, NULL);
INSERT INTO reward (lid, tier, revenue) VALUES (null, 'Tier 3', 0, NULL);
INSERT INTO reward (lid, tier, revenue) VALUES (null, 'Last 3 digit of Tier 1', 0, NULL);
INSERT INTO reward (lid, tier, revenue) VALUES (null, 'Last 2 digit (Random 2 digit)', 0, NULL);

CREATE TABLE IF NOT EXISTS payment (
    payid INT AUTO_INCREMENT PRIMARY KEY,
    uid INT NOT NULL,
    tier VARCHAR(20) NOT NULL,
    revenue DECIMAL(12, 2) NOT NULL,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE purchase ADD CONSTRAINT fk_purchase_user FOREIGN KEY (uid) REFERENCES user(uid) ON DELETE CASCADE;
ALTER TABLE purchase ADD CONSTRAINT fk_purchase_lottery FOREIGN KEY (lid) REFERENCES lottery(lid) ON DELETE CASCADE;
ALTER TABLE reward ADD CONSTRAINT fk_reward_lottery FOREIGN KEY (lid) REFERENCES lottery(lid) ON DELETE CASCADE;
ALTER TABLE payment ADD CONSTRAINT fk_payment_user FOREIGN KEY (uid) REFERENCES user(uid) ON DELETE CASCADE;

ALTER TABLE user ADD COLUMN token VARCHAR(255) IF NOT EXISTS;
-- ALTER TABLE reward DROP COLUMN winner;

COMMIT; 