services:
  prod-lottocat-api:
    build:
      context: .
      dockerfile: dockerFile
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE_IN=${JWT_EXPIRE_IN}
      - IS_SIGN=${IS_SIGN}
      - UPLOAD_TO_GCS=true
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - lotcatto

networks:
  lotcatto:
    driver: bridge