services:
  api:
    build:
      context: .
      dockerfile: dockerFile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - lotcatto

networks:
  lotcatto:
    driver: bridge