services:
  prod-lottocat-api:
    build:
      context: .
      dockerfile: dockerFile
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE_IN=${JWT_EXPIRE_IN}
      - IS_SIGN=${IS_SIGN}
      - UPLOAD_TO_GCS=true
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcs-key.json
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
    volumes:
      - ./gcs-key.json:/app/gcs-key.json:ro
    # volumes:
    #   - uploads:/app/uploads
    ports:
      - "3000:3000"
    networks:
      - lotcatto

# volumes:
#   uploads:

networks:
  lotcatto:
    driver: bridge